server:
  port: 8000
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      maxRequestSize: 100MB
  data:
    redis:
      host: localhost
      port: ${REDIS_BINDING_PORT}
      password:
  jpa:
    hibernate:
      ddl-auto: none
    #전송 쿼리 생성
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  datasource:
    url: ${MARIADB_LOCAL_URL}
    username: ${MARIADB_LOCAL_USER}
    password: ${MARIADB_LOCAL_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
jwt:
  issuer: bbanglebbangle
  secret_key: bbangleOven
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
      end-point: ${S3_END_POINT}
    credentials:
      access-key: ${S3_CREDENTIALS}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
      auto: false
    stack:
      auto: false

---
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:bakery;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
