server:
  port: 8000
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      maxRequestSize: 100MB
  data:
    redis:
      host: localhost
      port: ${REDIS_BINDING_PORT}
      password:
  jpa:
    hibernate:
      ddl-auto: none
    #전송 쿼리 생성
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  datasource:
    url: ${MARIADB_LOCAL_URL}
    username: ${MARIADB_LOCAL_USER}
    password: ${MARIADB_LOCAL_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${REDIRECT_URI}
    scope: email,profile
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    client-authentication-method: client_secret_post
    authorization-grant-type: authorization_code
    scope: profile_nickname, profile_image
    client_name: Kakao
jwt:
  issuer: bbanglebbangle
  secret_key: bbangleOven
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
      end-point: ${S3_END_POINT}
    credentials:
      access-key: ${S3_CREDENTIALS}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
      auto: false
    stack:
      auto: false

---
spring:
  config:
    activate:
      on-profile: production
  data:
    redis:
      host: localhost
      port: 6379
      password:
  jpa:
    show-sql: false
  datasource:
    url: jdbc:mariadb://115.85.181.105:3300/bakery?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 9893
    driver-class-name: org.mariadb.jdbc.Driver
oauth2:
  google:
    client-id: 191791280887-ij6l3b2eav7n2eibubo3pq0msahvha04.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://www.bbangle.store/login/oauth2/code/google
cloud:
  aws:
    s3:
      bucket: bbangle-bucket
      end-point: https://kr.object.ncloudstorage.com
    credentials:
      access-key: i0gjlRUfOrekFsXqNmbf
      secret-key: uc3cX2zcRi0lc56PfLLpMilETl5nvP25ipKcHVUb
    region:
      static: kr-standard
